<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - 127.0.0.1:62001</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>127.0.0.1:62001</h1>
<p>
  Test duration: 24.457s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">cn.crazy.appium.keyworddriver.TestSuiteByExcel</td>
      </tr>
            
<tr>
  <td class="method">
                  testTestSuite
      </td>
  <td class="duration">
    11.733s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: 执行出现异常，测试用例执行失败！</b></a><br />
    <div class="stackTrace" id="exception-0">
              org.testng.Assert.fail(Assert.java:94)<br />
              cn.crazy.appium.keyworddriver.TestSuiteByExcel.testTestSuite(TestSuiteByExcel.java:88)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:643)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:782)<br />
              org.testng.TestRunner.run(TestRunner.java:632)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:366)<br />
              org.testng.SuiteRunner.access$000(SuiteRunner.java:39)<br />
              org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)<br />
              org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br />
              java.util.concurrent.FutureTask.run(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br />
              java.lang.Thread.run(Unknown Source)<br />
                </div>
      </td>
</tr>
      </table>


  
</body>
</html>
